// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Karizma.Sample.Persistance.Repositories;

#nullable disable

namespace Karizma.Sample.Persistance.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20220403062955_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Karizma.Sample.Domain.Entities.Test.TestChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int?>("TestParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestParentId");

                    b.ToTable("TestChild", (string)null);
                });

            modelBuilder.Entity("Karizma.Sample.Domain.Entities.Test.TestParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("TestParent", (string)null);
                });

            modelBuilder.Entity("Karizma.Sample.Domain.Entities.Test.TestChild", b =>
                {
                    b.HasOne("Karizma.Sample.Domain.Entities.Test.TestParent", null)
                        .WithMany("TextChilderen")
                        .HasForeignKey("TestParentId");
                });

            modelBuilder.Entity("Karizma.Sample.Domain.Entities.Test.TestParent", b =>
                {
                    b.Navigation("TextChilderen");
                });
#pragma warning restore 612, 618
        }
    }
}
